### ISSUE TITLE
This library not working in iOS

### ISSUE THREAD

**Issue by congpc** [hexenq/kuroshiro#4]
- I use this library to integrate with Cordova for build iOS/android application. This library work in web, but not working in iOS.
- I debugged my application, and I saw errors when get values (buffers[0] and buffers[1]) of this method as:
`DictionaryLoader.prototype.load = function (load_callback) {
    var dic = this.dic;
    var dic_path = this.dic_path;
    var loadArrayBuffer = this.loadArrayBuffer;
    async.parallel([
        // Trie
        function (callback) {
            async.map([ "base.dat.gz", "check.dat.gz" ], function (filename, _callback) {
                loadArrayBuffer(path.join(dic_path, filename), function (err, buffer) {
                    if(err) {
                        return _callback(err);
                    }
                    _callback(null, buffer);
                });
            }, function (err, buffers) {
                if(err) {
                    return callback(err);
                }
                var base_buffer = new Int32Array(buffers[0]);
                var check_buffer = new Int32Array(buffers[1]);
                dic.loadTrie(base_buffer, check_buffer);
                callback(null);
            });
        },`
<a data-flickr-embed="true"  href="https://www.flickr.com/photos/93945798@N05/30562253332/in/dateposted-public/" title="Screen Shot 2016-10-31 at 10.27.27"><img src="https://c5.staticflickr.com/6/5612/30562253332_8e06b521cb_b.jpg" width="1024" height="784" alt="Screen Shot 2016-10-31 at 10.27.27"></a><script async src="//embedr.flickr.com/assets/client-code.js" charset="utf-8"></script>
- Can you help me to resolve this problem in iOS? 
Thank you very much.

**Comment by hexenq** [comment]
Thanks for your feedback, congpc. I want to help you out of this situation, but actually I have no experience with Cordova hybrid application. It looks like a cross-platform problem caused by different Javascript engine. See if we can find someone familiar with Cordova and ios who can handle your questions.

**Comment by atomworks** [comment]
I've just been experimenting with this on a prototype I'm building for an iOS app. If I run it on my Macbook then it works quickly and perfectly but running the init on iOS it takes a good few minutes to run this process. I'm not sure the code that this issue was using to implement but if you're trying to trigger actions before it's finished initialise you'll run in to tons of errors.

**Comment by hexenq** [comment]
The dictionary files are up to 17MB in size. So it may be overwhelming if kuroshiro.js is not initialized natively.

**Comment by retorquere** [comment]
I'm actually OK with 17MB dicts if I can get around the dynamic init. I am looking to use kuroshiro in a firefox extension and I cannot do dynamic loads using `require`.

**Comment by hexenq** [comment]
Hello @congpc . A new version 1.1.0 of kuroshiro has been released. By this update, you could use Yahoo Web API as an external morphological analyzer which might be a workaround to your question. Give it a try. 😉 You're welcome to raise another issue if needed. Closed.
